### ISSUE TITLE
Support for Redis Sentinels

### ISSUE THREAD

**Issue by davidor** [socketry/async-redis#28]
Are there any plans to add support for Redis sentinels? 
If there aren't, @ioquatix would you be open to accept contributions for this?

Refs:
https://redis.io/topics/sentinel
https://github.com/redis/redis-rb#sentinel-support

**Comment by ioquatix** [comment]
What kind of design makes the most sense to you, considering the current implementation?

**Comment by davidor** [comment]
Not sure yet. I'll try to find some time in the next days to experiment a bit.
For now, I've just adapted some code from redis-rb to resolve masters/slaves by asking the sentinels: https://github.com/davidor/async-redis/tree/sentinels
