### ISSUE TITLE
SSL/TLS Support?

### ISSUE THREAD

**Issue by machty** [socketry/async-redis#32]
Is it possible to pass in the `ssl_params` described [here](https://github.com/redis/redis-rb#ssltls-support) to the async-redis client?

**Comment by machty** [comment]
More specifically, I'm trying to get async-redis to talk to a new Heroku Redis v6 instance which is hosted on a `rediss://` URL, so I'm curious what our options are.

**Comment by ioquatix** [comment]
Yes, just use `Async::IO::Endpoint.ssl('localhost', port, ssl_context: ...)`.

**Comment by machty** [comment]
Thank you, that worked!

**Comment by ioquatix** [comment]
If you have time can you make a PR for the documentation?

**Comment by machty** [comment]
@ioquatix #33
