### ISSUE TITLE
Context::Pipeline#collect requires useless block

### ISSUE THREAD

**Issue by orlando-labs** [socketry/async-redis#39]
Hi, I found out Context::Pipeline#collect requires block:
https://github.com/socketry/async-redis/blob/da5a38cef1b84463f9374bab076006b88fa9a811/lib/async/redis/context/pipeline.rb#L93

What's the purpose of this yield? It does nothing but just the block execution.

**Comment by ioquatix** [comment]
Derp, that seems like a bug.

**Comment by ioquatix** [comment]
I'm admiring how long it took me to circle back to this. I've fixed it and added a test. Sorry about the wait.
