### ISSUE TITLE
Update gem dependencies so that it can depend on async 2.x

### ISSUE THREAD

**Issue by Maaarcocr** [socketry/async-redis#41]
Currently I think this line of the gemfile: https://github.com/socketry/async-redis/blob/de722da4457dc73d7d978fbfdbb99745bb1e517d/async-redis.gemspec#L16 is stopping this gem to depend on async 2.x

Is there a reason why this is anchored to 1.x? Could we use 2.x?

**Comment by ioquatix** [comment]
It should be fine both versions, feel free to make a PR to relax this dependency.
