### ISSUE TITLE
Redis cluster nodes, use IP or hostname?

### ISSUE THREAD

**Issue by travisbell** [socketry/async-redis#53]
Hey Samuel,

Nice work getting Redis cluster support! I've been playing around with migrating our usage of clusters and ran into a problem right away, which was due to DNS and the way Docker splits up networking. I can't always connect to the internal IP provided by the `cluster shards` command in Redis, but due to DNS and some port mapping, I _can_ always connect with a hostname.

https://github.com/socketry/async-redis/blob/6a75f890e67c57ff4d6417dc835379c13bf097d3/lib/async/redis/cluster_client.rb#L113

Is what I am talking about specifically. Changing line 113 to:

```ruby
endpoint = Endpoint.remote(node['hostname'], node['port'])
```

Fixes this issue for me.

So my question is, dev environment aside, should we use the IP here, or the hostname? How would this line currently handle a node being restarted and potentially grabbing a new IP on boot? I'm thinking of a real world example of upgrading a node in production, say with ElastiCache, I don't think there's any guarantee that the new node would come up with the same IP.

**Comment by travisbell** [comment]
Nevermind, I did some more investigating and IP's definitely seem like the way to go.

I'm closing this since it's invalid.

**Comment by ioquatix** [comment]
If this turns out to be a big issue, we could make it configurable or at least, introduce a method and allow a sub-class of `ClusterClient` to use a different implementation..?
