### ISSUE TITLE
Redis Cluster slot ranges

### ISSUE THREAD

**Issue by travisbell** [socketry/async-redis#54]
I noticed a very small percentage of my traffic was throwing an error, and I was confused as to why until I saw the code below. It's a subtle bug in the code that calculates the slot ranges:

https://github.com/socketry/async-redis/blob/6a75f890e67c57ff4d6417dc835379c13bf097d3/lib/async/redis/cluster_client.rb#L109

With `exclude_end` defined, the ranges are not including their last values.

```ruby
Range.new(*[12288, 16383], exclude_end: false)
=> 12288...16383
```

Whereas, we want to include the last values:

```ruby
Range.new(*[12288, 16383])
=> 12288..16383
```

This was causing the last slot for every node to not be found using `RangeMap#find`.

**Comment by ioquatix** [comment]
Sorry about this, that looks like a bug!

**Comment by ioquatix** [comment]
Fix released, please let me know how you get on.
